SIZE_INFO = 0x26
VPK_SIZE = 0x51
VPK = 0x53

PLUCKING_PIKMIN   = "PIKMINPUZZLE01".encode("ascii").ljust(16, b"\x00")
MARCHING_PIKMIN   = "PIKMINOTAKARA".encode("ascii").ljust(16, b"\x00")
CONNECTING_PIKMIN = "PIKMINPUZZLE02" .encode("ascii").ljust(16, b"\x00")

LEVEL_ID_LENGTH = 0x10

LEVELS_START = 0x100
LEVEL_FOOTER_LENGTH = 0x5

PLUCKING_PIKMIN_HEADER_LENGTH = 0x5
PLUCKING_PIKMIN_LAYER_LENGTH = 0x58
PLUCKING_PIKMIN_LENGTH = PLUCKING_PIKMIN_HEADER_LENGTH + PLUCKING_PIKMIN_LAYER_LENGTH * 2

# MARCHING_PIKMIN_LENGTH = UNK

CONNECTING_PIKMIN_HEADER_LENGTH = 0x3
CONNECTING_PIKMIN_LAYER_LENGTH = 0x36
CONNECTING_PIKMIN_LENGTH = CONNECTING_PIKMIN_HEADER_LENGTH + CONNECTING_PIKMIN_LAYER_LENGTH * 3
